apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
  namespace: default
  labels:
    app: nginx
  # backend: go
    podn: p2
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP
    env:
      - name: password
        valueFrom:
          configMapKeyRef:
            name: password
            key: password

